import { KeyRound, Mail, ShieldCheck } from "lucide-react";
import { type FormEvent, useState } from "react";
import { supabase } from "./supabase";

type Mode = "sign-in" | "sign-up" | "recovery" | "new-password";
export function AuthPanel({ recoveryActive }: { recoveryActive: boolean }) {
  const [mode, setMode] = useState<Mode>(recoveryActive ? "new-password" : "sign-in");
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!supabase) return;
    const form = new FormData(event.currentTarget); const email = String(form.get("email") || "").trim(); const password = String(form.get("password") || ""); const displayName = String(form.get("displayName") || "").trim();
    setError(null); setMessage(null); setLoading(true);
    try {
      if (mode === "sign-in") { const { error: result } = await supabase.auth.signInWithPassword({ email, password }); if (result) throw result; }
      else if (mode === "sign-up") { const { data, error: result } = await supabase.auth.signUp({ email, password, options: { data: displayName ? { display_name: displayName } : undefined, emailRedirectTo: window.location.origin } }); if (result) throw result; setMessage(data.session ? "Tu cuenta ya está lista." : "Revisa tu correo para confirmar la cuenta."); }
      else if (mode === "recovery") { const { error: result } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: window.location.origin }); if (result) throw result; setMessage("Si existe una cuenta con ese correo, recibirás las instrucciones de recuperación."); }
      else { const { error: result } = await supabase.auth.updateUser({ password }); if (result) throw result; setMessage("Contraseña actualizada. Ya puedes continuar."); }
    } catch (cause) { const text = cause instanceof Error ? cause.message : "No se pudo completar la operación."; setError(text.toLowerCase().includes("invalid login") ? "El correo o la contraseña no son correctos." : text); } finally { setLoading(false); }
  };
  const signUp = mode === "sign-up"; const recovery = mode === "recovery"; const newPassword = mode === "new-password";
  const title = signUp ? "Crea un espacio para tus finanzas." : recovery ? "Recupera tu acceso." : newPassword ? "Elige una contraseña nueva." : "Tu dinero, con calma y claridad.";
  return <main className="auth-page"><section className="auth-intro" aria-label="Financiera"><div className="brand"><span className="brand-mark">F</span><span>Financiera</span></div><div className="auth-intro-copy"><p className="eyebrow">CONTROL PERSONAL</p><h1>Una relación más clara con tu dinero.</h1><p>Tu información se protege por cuenta. Tú decides qué registrar y cómo organizarlo.</p></div><div className="auth-trust"><ShieldCheck aria-hidden="true" size={18} /><span>Sesión segura y datos aislados por usuario.</span></div></section><section className="auth-card-wrap" aria-live="polite"><form className="auth-card" onSubmit={submit}><p className="eyebrow">ACCESO PERSONAL</p><h2>{title}</h2><p className="auth-copy">{signUp ? "Empieza con lo esencial. Podrás ajustar tus preferencias después." : recovery ? "Te enviaremos un enlace para restablecer la contraseña." : newPassword ? "Usa una contraseña única y difícil de adivinar." : "Inicia sesión para continuar donde lo dejaste."}</p>{signUp && <label>Nombre visible<input name="displayName" autoComplete="name" maxLength={80} placeholder="Cómo quieres que te llamemos" /></label>}{!newPassword && <label>Correo electrónico<input name="email" type="email" autoComplete="email" required placeholder="tu@correo.com" /></label>}{!recovery && <label>Contraseña<input name="password" type="password" autoComplete={newPassword || signUp ? "new-password" : "current-password"} minLength={8} required placeholder="Mínimo 8 caracteres" /></label>}{error && <p className="auth-message auth-message--error" role="alert">{error}</p>}{message && <p className="auth-message" role="status">{message}</p>}<button className="primary-button auth-submit" disabled={loading} type="submit">{recovery ? <Mail aria-hidden="true" size={18} /> : <KeyRound aria-hidden="true" size={18} />}{loading ? "Un momento…" : signUp ? "Crear cuenta" : recovery ? "Enviar instrucciones" : newPassword ? "Guardar contraseña" : "Entrar"}</button>{!newPassword && <div className="auth-links">{mode === "sign-in" && <button type="button" onClick={() => setMode("recovery")}>¿Has olvidado la contraseña?</button>}{mode !== "sign-in" && <button type="button" onClick={() => setMode("sign-in")}>Volver a iniciar sesión</button>}{!recovery && <button type="button" onClick={() => setMode(signUp ? "sign-in" : "sign-up")}>{signUp ? "Ya tengo una cuenta" : "Crear una cuenta"}</button>}</div>}</form></section></main>;
}
