import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, CalendarDays } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { loadCalendarTransactions, type LedgerTransaction } from "./finance";
import type { FinancialAccount } from "./finance";

const dateKey = (date: Date) => date.toISOString().slice(0, 10);
const money = (value: number, currency: string) => new Intl.NumberFormat("es-ES", { style: "currency", currency }).format(value);
const dayTone = (items: LedgerTransaction[]) => { const balance = items.reduce((total, item) => total + Number(item.ledger_entries.find((entry) => entry.entry_kind === "account")?.amount ?? 0), 0); return balance > 0 ? "is-income" : balance < 0 ? "is-expense" : items.length ? "is-mixed" : ""; };
const monthValue = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
const monthLabel = (date: Date) => date.toLocaleDateString("es-ES", { month: "long", year: "numeric" });

export function CalendarWorkspace({ session, currency, accounts }: { session: Session; currency: string; accounts: FinancialAccount[] }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selected, setSelected] = useState(dateKey(new Date()));
  const [transactions, setTransactions] = useState<LedgerTransaction[]>([]);
  useEffect(() => { const from = new Date(month.getFullYear(), month.getMonth(), 1).toISOString().slice(0, 10); const to = new Date(month.getFullYear(), month.getMonth() + 1, 0).toISOString().slice(0, 10); void loadCalendarTransactions(session, from, to).then(setTransactions).catch(() => setTransactions([])); }, [month, session]);
  const days = useMemo(() => { const start = new Date(month); start.setDate(1 - ((start.getDay() + 6) % 7)); return Array.from({ length: 42 }, (_, index) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + index)); }, [month]);
  const selectedItems = transactions.filter((item) => item.effective_date === selected);
  const selectedBalances = useMemo(() => { const totals = new Map<string, number>(); for (const item of selectedItems) for (const entry of item.ledger_entries.filter((candidate) => candidate.entry_kind === "account")) totals.set(entry.currency_code, (totals.get(entry.currency_code) ?? 0) + Number(entry.amount)); return [...totals.entries()]; }, [selectedItems]);
  return <section className="calendar-workspace"><div className="section-heading"><div><p className="eyebrow">CALENDARIO</p><h1>Operaciones diarias</h1><p className="section-copy">Consulta qué movimientos se registraron cada día.</p></div><CalendarDays size={24} /></div><div className="calendar-layout"><article className="surface calendar-panel"><div className="month-controls month-controls--single"><button aria-label="Mes anterior" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft /></button><label className="month-picker-label"><span>{monthLabel(month)}</span><input aria-label="Mes y año" type="month" value={monthValue(month)} onChange={(event) => { const [year, selectedMonth] = event.target.value.split("-").map(Number); setMonth(new Date(year, selectedMonth - 1, 1)); }} /></label><button aria-label="Mes siguiente" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight /></button></div><div className="calendar-weekdays">{["L", "M", "X", "J", "V", "S", "D"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map((day) => { const key = dateKey(day); const items = transactions.filter((item) => item.effective_date === key); return <button key={key} className={`calendar-day ${dayTone(items)} ${day.getMonth() === month.getMonth() ? "" : "is-outside"} ${key === selected ? "is-selected" : ""}`} onClick={() => setSelected(key)}><span>{day.getDate()}</span>{items.length > 0 && <i>{items.length}</i>}</button>; })}</div></article><article className="surface calendar-detail"><p className="eyebrow">{new Date(`${selected}T00:00:00`).toLocaleDateString("es-ES", { weekday: "long", day: "numeric", month: "long" })}</p><h2>Operaciones del día</h2>{selectedItems.length ? <><div className="split-list calendar-operation-list">{selectedItems.map((item) => { const entry = item.ledger_entries.find((candidate) => candidate.entry_kind === "account"); const amount = Number(entry?.amount ?? 0); const tone = item.transaction_type === "income" ? "is-positive" : item.transaction_type === "expense" ? "is-negative" : "is-neutral"; return <div className={`calendar-operation ${tone}`} key={item.id}><span><strong>{item.description}</strong><small>{item.transaction_type} · {accounts.find((account) => account.id === entry?.account_id)?.name ?? "Cuenta archivada"} · {entry?.currency_code ?? currency}</small></span><b>{money(amount, entry?.currency_code ?? currency)}</b></div>; })}</div><div className="calendar-day-balance"><span>Balance del día</span><div>{selectedBalances.map(([code, amount]) => <strong className={amount >= 0 ? "positive" : "negative"} key={code}>{money(amount, code)}</strong>)}</div></div></> : <p className="budget-copy">No hay operaciones registradas en este día.</p>}</article></div></section>;
}
