import { ArrowDownLeft, ArrowUpRight, ChevronLeft, ChevronRight, Landmark, PiggyBank } from "lucide-react";
import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { chartCeiling, loadDashboardOverview, type DashboardOverview } from "./dashboard";
import { monthStart, shiftMonth } from "./budgets";
import { LoadingState } from "./LoadingState";

const money = (value: number, currency: string) => new Intl.NumberFormat("es-ES", { style: "currency", currency, maximumFractionDigits: 2 }).format(value);
const monthLabel = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("es-ES", { month: "short" });
const periodLabel = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("es-ES", { month: "long", year: "numeric" });

export function DashboardWorkspace({ currency, currencyControl, onCreateAccount }: { currency: string; currencyControl?: ReactNode; onCreateAccount: () => void }) {
  const [period, setPeriod] = useState(monthStart());
  const [data, setData] = useState<DashboardOverview | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; setData(null); setError(""); loadDashboardOverview(period, currency).then((value) => { if (active) setData(value); }).catch(() => { if (active) setError("No se pudo cargar el resumen. Vuelve a intentarlo."); }); return () => { active = false; }; }, [period, currency]);
  return <section className="dashboard-workspace"><div className="dashboard-heading"><div><p className="eyebrow">VISIÓN GENERAL</p><h1>Tu dinero, explicado sin ruido.</h1></div><div className="dashboard-period-controls">{currencyControl}<div className="month-controls month-controls--single"><button aria-label="Mes anterior" onClick={() => setPeriod(shiftMonth(period, -1))}><ChevronLeft size={18} /></button><label className="month-picker-label"><span>{periodLabel(period)}</span><input aria-label="Mes y año del resumen" type="month" value={period.slice(0, 7)} onChange={(event) => setPeriod(`${event.target.value}-01`)} /></label><button aria-label="Mes siguiente" onClick={() => setPeriod(shiftMonth(period, 1))}><ChevronRight size={18} /></button></div></div></div>{error ? <p className="inline-error" role="alert">{error}</p> : !data ? <LoadingState label="Actualizando el inicio…" /> : <DashboardData data={data} currency={currency} onCreateAccount={onCreateAccount} />}</section>;
}

function DashboardData({ data, currency, onCreateAccount }: { data: DashboardOverview; currency: string; onCreateAccount: () => void }) {
  const [slide, setSlide] = useState(0);
  const ceiling = chartCeiling(data.monthly); const budgetPct = data.budget.total_budget ? Math.max(0, Math.min(100, data.budget.budgeted_spent / data.budget.total_budget * 100)) : 0;
  const panels = [
    <article className="surface dashboard-slide" key="evolution"><div className="surface-heading"><div><p className="eyebrow">EVOLUCIÓN</p><h2>Ingresos y gastos</h2></div><span className="surface-badge">6 MESES</span></div><div className="bar-chart">{data.monthly.map((month) => <div className="bar-group" key={month.period_start}><div className="bars"><i className="bar-income" style={{ height: `${month.income / ceiling * 100}%` }} /><i className="bar-expense" style={{ height: `${month.expenses / ceiling * 100}%` }} /></div><small>{monthLabel(month.period_start)}</small></div>)}</div><p className="chart-legend"><span>Ingresos</span><span>Gastos</span></p></article>,
    <article className="surface dashboard-slide" key="budget"><div className="surface-heading"><div><p className="eyebrow">PRESUPUESTO</p><h2>Ritmo mensual</h2></div><PiggyBank size={20} /></div>{data.budget.total_budget ? <div className="dashboard-budget-focus"><strong className="budget-total">{money(data.budget.budgeted_spent, currency)}</strong><p className="budget-copy">de {money(data.budget.total_budget, currency)} presupuestados</p><div className="budget-track"><i style={{ width: `${budgetPct}%` }} /></div></div> : <div className="dashboard-empty"><PiggyBank size={24} /><p>Aún no hay presupuestos para este mes.</p></div>}</article>,
    <article className="surface dashboard-slide" key="activity"><div className="surface-heading"><div><p className="eyebrow">ACTIVIDAD</p><h2>Últimos movimientos</h2></div><Landmark size={20} /></div>{data.recent_transactions.length ? <div className="dashboard-list">{data.recent_transactions.map((item) => <div key={item.id}><span className={item.amount >= 0 ? "positive" : "negative"}>{item.amount >= 0 ? <ArrowDownLeft size={16} /> : <ArrowUpRight size={16} />}</span><p><strong>{item.description}</strong><small>{new Date(`${item.effective_date}T00:00:00`).toLocaleDateString("es-ES")} · {item.category_name ?? "Sin categoría"}</small></p><b className={item.amount >= 0 ? "positive" : "negative"}>{money(item.amount, currency)}</b></div>)}</div> : <div className="dashboard-empty"><Landmark size={24} /><p>No hay movimientos en este período.</p>{!data.active_accounts && <button className="secondary-button" onClick={onCreateAccount}>Crear cuenta</button>}</div>}</article>,
  ];
  return <><div className="metrics-grid dashboard-metrics"><Metric label="Disponible ahora" value={money(data.available, currency)} detail={`${data.active_accounts} cuentas activas`} /><Metric label="Ingresos" value={money(data.income, currency)} detail="Entrada del periodo" positive /><Metric label="Gastos" value={money(data.expenses, currency)} detail="Salida del periodo" /><Metric label="Ahorro neto" value={money(data.balance, currency)} detail={data.balance >= 0 ? "El mes respira bien" : "Conviene revisar gastos"} positive={data.balance >= 0} /></div><div className="dashboard-carousel"><div className="dashboard-carousel-heading"><span>Informes del periodo</span><div><button type="button" aria-label="Informe anterior" onClick={() => setSlide((slide + panels.length - 1) % panels.length)}><ChevronLeft size={17} /></button><span>{slide + 1} / {panels.length}</span><button type="button" aria-label="Informe siguiente" onClick={() => setSlide((slide + 1) % panels.length)}><ChevronRight size={17} /></button></div></div><div className="dashboard-carousel-track" style={{ transform: `translateX(-${slide * 100}%)` }}>{panels}</div><div className="dashboard-carousel-dots">{panels.map((panel, index) => <button type="button" key={panel.key} className={index === slide ? "is-active" : ""} aria-label={`Ver informe ${index + 1}`} onClick={() => setSlide(index)} />)}</div></div></>;
}
function Metric({ label, value, detail, positive = false }: { label: string; value: string; detail: string; positive?: boolean }) { return <article className="metric-card"><p>{label}</p><strong>{value}</strong><span className={positive ? "metric-detail metric-detail--positive" : "metric-detail"}>{detail}</span></article>; }
