import type { Session } from "@supabase/supabase-js";
import { supabase } from "./supabase";
export type GoalStatus = "active"|"paused"|"completed"|"archived";
export type GoalPriority = "low"|"normal"|"high";
export type ContributionFrequency = "none"|"weekly"|"monthly";
export type GoalTrackingMode = "manual"|"account_balance";
export type Goal = { id:string; name:string; target_amount:number; currency_code:string; target_date:string|null; status:GoalStatus; priority:GoalPriority; contribution_frequency:ContributionFrequency; tracking_mode:GoalTrackingMode; linked_account_id:string|null; linked_account_name:string|null; contributed:number; remaining:number; progress_pct:number };
export type GoalContribution = { id:string; goal_id:string; amount:number; contributed_on:string; note:string|null };
export type GoalInput = { name:string; target_amount:number; currency_code:string; target_date:string|null; priority:GoalPriority; contribution_frequency:ContributionFrequency; tracking_mode:GoalTrackingMode; linked_account_id:string|null };
function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase;}
export async function loadGoals(){const {data,error}=await client().rpc("get_savings_goals_overview");if(error)throw error;return (data??[]).map((g:Goal)=>({...g,target_amount:Number(g.target_amount),contributed:Number(g.contributed),remaining:Number(g.remaining),progress_pct:Number(g.progress_pct)})) as Goal[];}
export async function createGoal(session:Session,input:GoalInput){const {error}=await client().from("savings_goals").insert({user_id:session.user.id,...input,name:input.name.trim(),target_date:input.target_date||null});if(error)throw error;}
export async function contribute(session:Session,goalId:string,amount:number,note:string){const {error}=await client().from("goal_contributions").insert({user_id:session.user.id,goal_id:goalId,amount,note:note.trim()||null});if(error)throw error;}
export async function loadContributions(goalIds:string[]){if(!goalIds.length)return [];const {data,error}=await client().from("goal_contributions").select("id,goal_id,amount,contributed_on,note").in("goal_id",goalIds).order("contributed_on",{ascending:false});if(error)throw error;return (data??[]).map((row)=>({...row,amount:Number(row.amount)})) as GoalContribution[];}
export async function loadGoalAccounts(session:Session,currency:string){const {data,error}=await client().from("financial_accounts").select("id,name").eq("user_id",session.user.id).eq("currency_code",currency).eq("is_active",true).order("name");if(error)throw error;return (data??[]) as {id:string;name:string}[];}
export async function updateGoal(session:Session,goalId:string,input:Partial<GoalInput>&{status?:GoalStatus}){const payload={...input};if(payload.name!==undefined)payload.name=payload.name.trim();if(payload.target_date==="")payload.target_date=null;const {error}=await client().from("savings_goals").update(payload).eq("id",goalId).eq("user_id",session.user.id);if(error)throw error;}
export function goalRhythm(contributions:GoalContribution[],today=new Date()){const start=new Date(today.getFullYear(),today.getMonth(),today.getDate()-30,12);const recent=contributions.filter((item)=>new Date(`${item.contributed_on}T12:00:00`)>=start).length;if(recent===0)return "Sin aportaciones en los últimos 30 días.";return recent===1?"Una aportación en los últimos 30 días.":`${recent} aportaciones en los últimos 30 días.`;}
