import type { Session } from "@supabase/supabase-js";
import { supabase } from "./supabase";

export type ImportRowStatus = "ready" | "invalid" | "duplicate";
export type ImportPreviewRow = { row_number:number; raw:Record<string,string>; effective_date:string|null; description:string|null; amount:number|null; transaction_type:"income"|"expense"|null; category_id:string|null; fingerprint:string|null; status:ImportRowStatus; error_message:string|null };
export type ImportRowRecord = ImportPreviewRow & { id:string; batch_id:string };
export type CategorizationRule = { id:string; name:string; match_text:string; transaction_type:"income"|"expense"|null; category_id:string; priority:number; is_active:boolean };

function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase;}
export function splitCsvLine(line:string){const cells:string[]=[];let current="",quoted=false;for(let i=0;i<line.length;i+=1){const char=line[i];if(char==="\""&&line[i+1]==="\""){current+="\"";i+=1;}else if(char==="\""){quoted=!quoted;}else if(char===","&&!quoted){cells.push(current.trim());current="";}else current+=char;}cells.push(current.trim());return cells;}
export function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter((line)=>line.trim());if(lines.length<2)return[];const headers=splitCsvLine(lines[0]).map((h)=>h.toLowerCase().trim());return lines.slice(1).map((line)=>Object.fromEntries(splitCsvLine(line).map((cell,index)=>[headers[index]||`col_${index+1}`,cell])));}
const pick=(row:Record<string,string>,names:string[])=>names.map((name)=>row[name]).find((value)=>value!==undefined&&value.trim()!=="")?.trim()??"";
function hash(text:string){let value=0;for(let i=0;i<text.length;i+=1)value=(Math.imul(31,value)+text.charCodeAt(i))|0;return `imp_${Math.abs(value).toString(36)}`;}
export function normalizeImportRows(rows:Record<string,string>[],rules:CategorizationRule[]=[]):ImportPreviewRow[]{const seen=new Set<string>();return rows.map((raw,index)=>{const date=pick(raw,["date","fecha","effective_date","fecha operacion"]);const description=pick(raw,["description","descripcion","concepto","detalle","merchant"]);const rawAmount=pick(raw,["amount","importe","valor","cantidad"]).replace(",",".");const parsed=Number(rawAmount);const amount=Number.isFinite(parsed)?Math.abs(parsed):null;const transaction_type=amount===null?null:parsed<0?"expense":"income";const fingerprint=date&&description&&amount!==null?hash(`${date}|${description.toLowerCase()}|${amount}|${transaction_type}`):null;const rule=rules.filter((r)=>r.is_active&&(!r.transaction_type||r.transaction_type===transaction_type)).sort((a,b)=>a.priority-b.priority).find((r)=>description.toLowerCase().includes(r.match_text.toLowerCase()));let status:ImportRowStatus="ready";let error_message:string|null=null;if(!date||!description||amount===null||!transaction_type){status="invalid";error_message="Fecha, concepto o importe no reconocidos";}else if(fingerprint&&seen.has(fingerprint)){status="duplicate";error_message="Duplicado dentro del archivo";}if(fingerprint)seen.add(fingerprint);return{row_number:index+1,raw,effective_date:date||null,description:description||null,amount,transaction_type,category_id:rule?.category_id??null,fingerprint,status,error_message};});}
export async function loadCategorizationRules(session:Session){const {data,error}=await client().from("categorization_rules").select("id,name,match_text,transaction_type,category_id,priority,is_active").eq("user_id",session.user.id).order("priority");if(error)throw error;return (data??[]) as CategorizationRule[];}
export async function createCategorizationRule(session:Session,input:{name:string;match_text:string;transaction_type:"income"|"expense"|"";category_id:string;priority:number}){const {error}=await client().from("categorization_rules").insert({user_id:session.user.id,name:input.name.trim(),match_text:input.match_text.trim(),transaction_type:input.transaction_type||null,category_id:input.category_id,priority:input.priority});if(error)throw error;}
export async function setCategorizationRuleActive(session:Session,id:string,is_active:boolean){const {error}=await client().from("categorization_rules").update({is_active}).eq("id",id).eq("user_id",session.user.id);if(error)throw error;}
export async function createImportBatch(session:Session,accountId:string,fileName:string,rows:ImportPreviewRow[]){const {data,error}=await client().from("import_batches").insert({user_id:session.user.id,account_id:accountId,file_name:fileName,source_type:fileName.toLowerCase().endsWith(".csv")?"csv":"excel_csv"}).select("id").single();if(error)throw error;const batchId=data.id as string;const {error:rowsError}=await client().from("import_rows").insert(rows.map((row)=>({user_id:session.user.id,batch_id:batchId,row_number:row.row_number,raw_payload:row.raw,effective_date:row.effective_date,description:row.description,amount:row.amount,transaction_type:row.transaction_type,category_id:row.category_id,fingerprint:row.fingerprint,status:row.status,error_message:row.error_message})));if(rowsError)throw rowsError;return batchId;}
export async function confirmImportBatch(batchId:string){const {data,error}=await client().rpc("confirm_import_batch",{p_batch_id:batchId});if(error)throw error;return data as {imported:number;duplicates:number;invalid:number};}
